version: "3"

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./web:/web
      - /web/node_modules
    environment:
      - VITE_API_URL=http://localhost:4000
    depends_on:
      - api
    container_name: web
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./api:/api
      - /api/node_modules
    container_name: api
